# Generated by Django 3.0.2 on 2020-03-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('ip', models.GenericIPAddressField(protocol='IPv4')),
                ('mac', models.CharField(max_length=12)),
                ('notes', models.TextField()),
            ],
        ),
    ]
