# Generated by Django 3.0.2 on 2020-02-18 15:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('duration', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), size=None)),
                ('value', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('notes', models.TextField()),
            ],
        ),
    ]
