# Generated by Django 3.0.2 on 2020-03-03 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_series', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeseries',
            old_name='duration',
            new_name='time',
        ),
    ]
