# Generated by Django 3.0.2 on 2020-03-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_series', '0002_auto_20200303_0428'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeseries',
            name='interval',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
